services:
  - type: web
    name: tasktogether-backend
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
